[package]
name = "dprint-plugin-sort-package-json"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Sorts package.json files for dprint."
homepage = "https://github.com/colinaaa/dprint-plugin-sort-package-json"
repository = "https://github.com/colinaaa/dprint-plugin-sort-package-json"

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"

[features]
wasm = ["serde_json", "dprint-core/wasm"]

[dependencies]
anyhow = "1.0.104"
dprint-core = { version = "0.69.1", features = ["wasm"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["preserve_order"], optional = true }
sort-package-json = "1.0.0"

[dev-dependencies]
dprint-development = "0.11.0"
serde_json = { version = "1.0.151" }
